version: '3'
services:
   frontend:
      container_name: react
      build:
         context: './Web-Frontend'
         dockerfile: './Dockerfile.dev'
      networks:
         - network
   backend:
      container_name: express
      restart: always
      build: 
         context: './Backend'
         dockerfile: './Dockerfile.dev'
      ports:
         - '3000:3000'
      depends_on:
         - db
      networks:
         - network
   db:
      container_name: mongo
      image: mongo
      ports:
         - '27017:27017'
      networks:
         - network

   nginx:
      restart: always
      build:
         dockerfile: Dockerfile.dev
         context: ./Nginx
      ports:
         - '80:80'
      networks:
         - network
networks: 
  network:
    driver: bridge